// Bundle docs/*.md into a TS module the web app can import.
// Runs before next dev + next build.
//
// Each .md file becomes one DocEntry. Slug = lowercased filename minus
// extension, with underscores replaced by hyphens. Title = first H1 line
// (or filename fallback). Description = first paragraph after the title.

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..", "..", "..");
const DOCS_DIR  = resolve(REPO_ROOT, "docs");
const OUT_FILE  = resolve(__dirname, "..", "src", "lib", "docs.generated.ts");

function slugify(filename) {
  return filename
    .replace(/\.md$/i, "")
    .toLowerCase()
    .replace(/_/g, "-");
}

function extractTitle(md, fallback) {
  const m = md.match(/^#\s+(.+?)\s*$/m);
  return m ? m[1].trim() : fallback;
}

function extractDescription(md) {
  // First non-empty, non-heading paragraph after the H1
  const afterH1 = md.split(/^#\s.+$/m).slice(1).join("\n").trim();
  const blocks = afterH1.split(/\n\s*\n/);
  for (const block of blocks) {
    const trimmed = block.trim();
    if (!trimmed) continue;
    if (trimmed.startsWith("#")) continue;
    if (trimmed.startsWith(">")) continue;
    if (trimmed.startsWith("|")) continue;
    // Strip basic markdown for the index card teaser
    const plain = trimmed.replace(/[*_`#>[\]()]/g, "").slice(0, 280);
    return plain;
  }
  return "";
}

const files = readdirSync(DOCS_DIR)
  .filter((f) => f.toLowerCase().endsWith(".md"));

const entries = files
  .map((filename) => {
    const path = join(DOCS_DIR, filename);
    const content = readFileSync(path, "utf-8");
    const slug = slugify(filename);
    const title = extractTitle(content, filename.replace(/\.md$/i, ""));
    const description = extractDescription(content);
    return { slug, filename, title, description, content };
  })
  // README first if present, then alphabetical by title
  .sort((a, b) => {
    if (a.slug === "readme") return -1;
    if (b.slug === "readme") return 1;
    return a.title.localeCompare(b.title);
  });

const body = `// AUTO-GENERATED by apps/web/scripts/build-docs.mjs — do not edit by hand.
// Re-run \`npm run docs:build\` after changing files in /docs.

export interface DocEntry {
  slug: string;
  filename: string;
  title: string;
  description: string;
  content: string;
}

export const DOCS: DocEntry[] = ${JSON.stringify(entries, null, 2)};

export function findDoc(slug: string): DocEntry | undefined {
  return DOCS.find((d) => d.slug === slug);
}
`;

mkdirSync(dirname(OUT_FILE), { recursive: true });
writeFileSync(OUT_FILE, body, "utf-8");

console.log(`[docs] bundled ${entries.length} doc(s) -> ${OUT_FILE}`);
for (const e of entries) {
  console.log(`  /docs/${e.slug.padEnd(20)} ${e.title}`);
}
