/**
 * Per-lesson QUIZ SKIN (LP-15): CSS generated by the designer AI so quiz
 * scenes align with the lesson's video beats in branding, fonts, sizes and
 * backgrounds — the essence/presentation split.
 *
 *   essence      = the quiz engine (interactions, grading, feedback flow)
 *   presentation = this skin, targeting the .qz-* class contract
 *                  (docs/quiz-skin-contract.md)
 *
 * Generated lazily at publish; stored at lessons/<id>/quiz-skin.css.
 * lintQuizSkin gates it — a failing skin is dropped and the palette
 * default ships, so a bad skin can never break a lesson.
 */

import { eq } from "drizzle-orm";
import { lintQuizSkin } from "@lp/scorm-packager";

import { db, tables } from "../db/index.js";
import { s3 } from "./s3.js";
import { getStylePalette } from "./hf-designer.js";
import { getRulesBlock } from "./rules.js";
import type { createAIClient } from "@lp/ai-provider";

type AIClient = ReturnType<typeof createAIClient>;

/** Distilled from the Genially quiz-template scout (docs/quiz-scout-report.md,
 *  8 templates, scouted 2026-07-06). */
const SCOUT_VOCAB = `
## Genially quiz house style (scouted from their 8 quiz templates — apply this vocabulary)
- STRUCTURE FORMULA: stage → surface → chips. Either one big rounded "sheet"
  on a flat saturated/patterned field, or a full-bleed color field with no
  surfaces. Radius shrinks outward-in (sheet ~0.7em → cards ~0.4em → pills).
  No borders or heavy shadows — separate by value/hue steps; at most one tiny
  shadow (0 1px 0.25em rgba(18,18,18,0.2)).
- PATTERNED BACKGROUND: a subtle tiled geometric motif (diamond lattice, dots,
  weave) in one theme color over another at 10-20% opacity on .quiz-scene is
  the house anti-flatness device. CSS gradients/repeating-linear-gradient or
  data-URI SVG tiles only.
- TWO-STEP TYPE SCALE, max two families: display prompt 4:1 to 7:1 over body,
  either a personality face for .qz-q + neutral sans for the rest, or one
  family at weight 300 vs 800. Helper text demoted by muted color, not size.
- ACCENT ECONOMY, tiered: play surfaces near-monochrome; accent-A on
  interactive chips/options, accent-B ONLY on Submit/Continue (.qz-go).
  The brightest object on screen must be the pressable one.
- CHIP SYSTEM: option chips = 1px solid accent border + accent at ~11% alpha
  fill + accent text. Drop zones reuse the SAME border color at card scale
  (border rhyme says "this goes in that"). Holding areas dashed, destinations
  solid and mostly empty.
- HOVER GRAMMAR IS SEMANTIC: grow (scale 1.06) = grabbable · shrink (0.95) =
  pressable · float (translateY(-0.2em)) = CTA. Transitions:
  0.2s cubic-bezier(0.4, 0, 0.4, 1).
- FEEDBACK FORMULA: pale same-hue tint bg + saturated same-hue border/ink —
  e.g. correct ink #25A782 on #E5FAF4, wrong ink #D83F55 on #FAE6E6, or
  desaturated pastels (sage #AEE0B0 / terracotta #D5725F) tinted toward the
  brand. NEVER solid green/red slabs. Right and wrong must differ by more
  than hue.
- SIGNATURE MOVES to pick 1-2 of (not all): letterbox bars in ink at frame
  top/bottom; a colored header band fused to the question area; the .qz-deco
  glyph swapped for a topic-relevant character; cloze gaps as tinted
  rectangles; an italic accent subtitle; brick-staggered option grids
  (nth-child(even) translateY); stadium chips (radius 999).
- GAME FRAMING over test framing: the scene should feel like a place or a
  device, not a form.
`;

const SKIN_SYSTEM = `You design QUIZ SKINS: a single CSS stylesheet that restyles in-video quiz scenes so they look like they were designed by the same hand as the lesson's animated video beats.

You are styling a fixed DOM (the "quiz engine"). Its class contract:
- Scene: .quiz-scene (root, holds CSS vars --q-bg --q-ink --q-muted --q-accent --q-surface --q-line --q-accent-soft --q-accent-faint --q-btn-ink), .qz-frame (16:9 content frame), .qz-deco (decorative background glyph), .qz-rule, .qz-eyebrow, .qz-howto, .qz-q (.qz-q.long)
- Interactions: .qz-opts (+layout classes .tf .fi .hs .match .ord .sort .wb .sc .lk .fc .img .est .mem .tot .ws .gc), .qz-opt (.k letter chip), .qz-chip, .qz-input, .qz-answer-chip, .qz-go, .qz-fb
- Style-specific: .qz-match-term .qz-match-slot .qz-match-card, .qz-bucket, .qz-wb-slot .qz-wb-bank, .qz-sc-panel, .qz-lk-seg, .qz-fc-card .qz-fc-face, .qz-mem-card, .qz-tot-card .qz-tot-dot, .qz-ws-cell .qz-ws-word, .qz-gc-hint
- State classes the engine toggles (style, never suppress): .sel .correct .wrong .found .got .matched .miss .down .flipped .on .used .badged .path .no .dragging .drop-hover .settled .in

IMPORTANT: the engine sets the --q-* variables INLINE on .quiz-scene per cue
(from the lesson palette), so redefining --q-* in your CSS has no effect.
You receive the same palette below — design WITH it; where you want a
different treatment, style the components directly (e.g. .qz-opt { background: ... }).

HARD RULES (a linter rejects violations and your skin is discarded):
- Every selector must contain .quiz-scene or a .qz- class. Nothing outside that scope.
- NEVER: display:none, visibility:hidden, pointer-events, position:fixed, position:sticky, @import, url(http...), script/markup.
- Keep .correct visibly green-family and .wrong red-family (may be tinted toward the brand, but right/wrong must differ by more than hue).
- Max ~180 lines. Sizes in em (the scene's em unit scales with the frame).
${SCOUT_VOCAB}
## Output
Reply with ONLY the CSS. No markdown fences, no commentary.`;

function extractCss(text: string): string {
  // Strip accidental fences; keep the largest CSS-looking chunk.
  const fenced = text.match(/```(?:css)?\s*([\s\S]*?)```/);
  return (fenced ? fenced[1]! : text).trim();
}

export async function ensureQuizSkin(
  ai: AIClient,
  lessonId: string,
  opts: { lessonTitle: string; styleHint?: string },
): Promise<string | null> {
  const key = `lessons/${lessonId}/quiz-skin.css`;
  // Reuse a previously generated skin (delete the object to force regen).
  try {
    const existing = await s3.getObject(key);
    const css = Buffer.from(existing.body).toString("utf-8");
    if (lintQuizSkin(css).ok) return css;
  } catch { /* not generated yet */ }

  const lesson = await db.query.lessons.findFirst({ where: eq(tables.lessons.id, lessonId) });
  const palette = getStylePalette(opts.styleHint);
  const rules = await getRulesBlock("designer");
  const brief = lesson?.designBrief ? `\nLesson design brief (the beats follow this — the skin must too):\n${lesson.designBrief}` : "";

  let lintNote = "";
  for (let attempt = 1; attempt <= 2; attempt++) {
    try {
      const res = await ai.chat("designer", {
        messages: [
          { role: "system", content: SKIN_SYSTEM + rules },
          { role: "user", content: `Lesson: "${opts.lessonTitle}"
Style: ${opts.styleHint ?? "swiss-grid"}
Palette (the beats use exactly these): bg ${palette.bg} · ink ${palette.ink} · muted ${palette.muted} · accent ${palette.accent} · surface ${palette.surface}${brief}

Design the quiz skin. Refine, don't fight, the palette: you may deepen shadows, add a background motif on .quiz-scene/.qz-deco, reshape cards/chips/buttons, tune the type scale — everything within the contract.${lintNote}` },
        ],
        meta: { lessonId },
      });
      const css = extractCss(res.text);
      const lint = lintQuizSkin(css);
      if (lint.ok) {
        await s3.putObject(key, Buffer.from(css, "utf-8"), { contentType: "text/css" });
        console.log(`[quiz-skin] generated for lesson ${lessonId} (${css.length} chars, attempt ${attempt})`);
        return css;
      }
      lintNote = `\n\nYour previous attempt FAILED lint — fix these and output the full corrected CSS:\n- ${lint.errors.join("\n- ")}`;
      console.warn(`[quiz-skin] attempt ${attempt} failed lint: ${lint.errors.join("; ")}`);
    } catch (err) {
      console.warn(`[quiz-skin] generation failed (publish proceeds with default styling):`, err instanceof Error ? err.message : err);
      return null;
    }
  }
  return null;
}
