/**
 * Text-to-speech via OpenAI's audio.speech API. Returns the MP3 bytes and
 * the actual playback duration (probed via ffprobe).
 *
 * OpenAI TTS is the cheapest reliable narration source we have right now
 * ($0.015 per 1K chars), works in browsers natively (MP3), and has the
 * teacher-ish voices we like (`onyx`, `nova`, `alloy`).
 */

import { spawn } from "node:child_process";
import OpenAI from "openai";

import { getSecret } from "./secrets.js";

export type TtsVoice = "alloy" | "echo" | "fable" | "onyx" | "nova" | "shimmer";

export interface TtsResult {
  audio: Buffer;
  /** MP3 duration in seconds, probed from the generated bytes via ffprobe. */
  durationSec: number;
}

export interface TtsOptions {
  voice?: TtsVoice;
  /** 0.25–4.0; 1.0 = natural. We default to 0.95 for the patient-teacher pace. */
  speed?: number;
  /** "tts-1" (faster, cheaper) or "tts-1-hd" (slightly better quality). */
  model?: "tts-1" | "tts-1-hd";
}

export async function synthesize(text: string, opts: TtsOptions = {}): Promise<TtsResult> {
  const key = await getSecret("openai_api_key");
  if (!key) throw new Error("OpenAI API key is not configured (set OPENAI_API_KEY or save it in Settings).");

  const client = new OpenAI({ apiKey: key });
  const res = await client.audio.speech.create({
    model: opts.model ?? "tts-1",
    voice: opts.voice ?? "onyx",
    input: text,
    speed: opts.speed ?? 0.95,
    response_format: "mp3",
  });
  const audio = Buffer.from(await res.arrayBuffer());
  const durationSec = await probeDuration(audio);
  return { audio, durationSec };
}

/** Run ffprobe on raw MP3 bytes via stdin, return duration in seconds. */
async function probeDuration(audio: Buffer): Promise<number> {
  return new Promise((resolve, reject) => {
    const ff = spawn("ffprobe", [
      "-v", "error",
      "-show_entries", "format=duration",
      "-of", "default=noprint_wrappers=1:nokey=1",
      "-i", "-",
    ]);
    let out = "";
    let err = "";
    ff.stdout.on("data", (b) => { out += b.toString(); });
    ff.stderr.on("data", (b) => { err += b.toString(); });
    ff.on("close", (code) => {
      if (code !== 0) return reject(new Error(`ffprobe exited ${code}: ${err.slice(0, 200)}`));
      const n = parseFloat(out.trim());
      if (!isFinite(n)) return reject(new Error(`ffprobe returned non-number: ${out}`));
      resolve(n);
    });
    ff.on("error", reject);
    ff.stdin.end(audio);
  });
}
